[supervisord]
nodaemon=true

[program:update_cloudflare_ip]
command=python update_cloudflare_ip.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

# The picard.py script will only be launched when SSH connections are made
# through the .bashrc mechanism, not as a background service